racine:
  path: /
  controller: App\Controller\RacineController::index

logout:
  path: /logout

login:
  path: /login
  controller: App\Controller\SecurityController::login

register:
  path: /register
  controller: App\Controller\RegistrationController::register

home:
  path: /user/home
  controller: App\Controller\DefaultController::index

pronostic:
  path: /user/pronostic
  controller: App\Controller\DefaultController::index

resultats:
  path: /user/resultats
  controller: App\Controller\DefaultController::index

profil:
  path: /user/profil
  controller: App\Controller\DefaultController::index

leaderboard:
  path: /user/classement
  controller: App\Controller\DefaultController::index

admin:
  path: /admin
  controller: App\Controller\DefaultController::index

adminClub:
  path: /admin/club
  controller: App\Controller\DefaultController::index

adminPronostics:
  path: /admin/pronostics
  controller: App\Controller\DefaultController::index
